from org.jbox2d.common import Vec2
from Level import Level
from Level import LevelLoadingScript
from Entity import EntityFactory
from Level import EntityContainer
from java.awt.geom import Point2D

def spawnEntity(world, factory, entityContainer, name, position):
	id = entityContainer.createNewEntity()
	components = entityContainer.accessComponents(id)
	mask = factory.createEntity(world, name, position, components)
	entityContainer.setEntityMask(id, mask)

class LevelLoader(LevelLoadingScript):
	def loadLevel(self, level):
		level.name = "Level1.2"
		level.m_size = Vec2(30.0, 20.0)
		level.m_gravity = Vec2(0.0,9.81)

	def createEntities(self, world, factory, entityContainer):
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 1.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 2.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 3.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 4.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 5.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 6.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 7.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 8.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 9.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 10.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 11.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 12.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 13.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 14.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 15.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 16.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 17.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 18.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(0.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(1.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(2.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(3.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(4.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(5.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(6.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(7.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(8.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(9.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(10.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(11.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(12.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(13.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(14.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(15.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(16.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(17.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(18.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(19.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(20.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(21.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(22.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(23.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(24.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(25.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(26.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(27.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(28.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 19.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 18.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 17.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 16.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 15.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 14.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 13.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 12.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 11.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 10.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 9.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 8.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 7.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 6.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 5.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 4.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 3.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 2.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 1.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(29.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(28.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(27.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(26.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(25.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(24.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(23.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(22.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(21.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(20.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(19.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(18.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(17.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(16.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(15.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(14.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(13.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(12.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(11.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(10.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(9.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(8.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(7.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(6.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(5.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(4.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(3.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(2.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(1.5, 0.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(1.5, 15.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(2.5, 15.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(3.5, 15.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(4.5, 15.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(5.5, 15.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(6.5, 15.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(7.5, 15.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(8.5, 15.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(10.5, 11.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(11.5, 11.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(12.5, 11.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(13.5, 11.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(14.5, 11.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(15.5, 11.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(21.5, 9.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(22.5, 9.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(23.5, 9.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(24.5, 9.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(25.5, 9.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(26.5, 9.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(27.5, 9.5))
		spawnEntity(world, factory, entityContainer, "Breaking Block", Vec2(28.5, 9.5))
		spawnEntity(world, factory, entityContainer, "Player", Vec2(18.5, 5.5))

