from org.jbox2d.common import Vec2
from Level import Level
from Level import LevelLoadingScript
from Entity import EntityFactory
from Level import World
from java.awt.geom import Point2D

def spawnEntity(world, factory, name, position):
	id = world.createNewEntity()
	components = world.accessComponents(id)
	mask = factory.createEntity(name, position, components)
	world.setEntityMask(id, mask)

class LevelLoader(LevelLoadingScript):
	def loadLevel(self, level):
		level.name = "SomeLevel"
		level.m_size = Vec2(25.0, 18.75)
		level.m_gravity = (0.0,9.81)

	def createEntities(self, factory, world):
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(1.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(2.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(3.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(4.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(5.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(6.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(7.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(8.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(9.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(10.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(11.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(12.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(13.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(14.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(15.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(23.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(22.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(21.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(20.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(19.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(18.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(17.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(16.0, 18.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 17.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 16.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 15.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 14.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 13.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 12.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 11.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 10.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 9.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 8.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 7.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 6.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 5.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 4.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 3.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 1.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(24.0, 2.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(23.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(22.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(21.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(20.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(19.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(18.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(17.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(16.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(15.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(14.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(13.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(12.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(11.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(10.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(9.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(8.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(7.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(6.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(5.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(4.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(3.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(2.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(1.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 0.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 1.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 2.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 3.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 4.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 5.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 6.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 7.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 8.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 9.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 10.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 11.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 12.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 13.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 14.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 15.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 16.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(0.0, 17.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(1.0, 11.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(2.0, 11.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(3.0, 11.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(4.0, 11.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(5.0, 11.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(6.0, 11.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(15.0, 13.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(16.0, 13.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(17.0, 13.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(18.0, 13.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(19.0, 13.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(20.0, 13.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(10.0, 6.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(11.0, 6.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(12.0, 6.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(13.0, 6.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(14.0, 6.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(15.0, 6.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(20.0, 8.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(21.0, 8.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(22.0, 8.0))
		spawnEntity(world, factory, "Normal Block", Point2D.Double(23.0, 8.0))
		spawnEntity(world, factory, "Player", Point2D.Double(8.0, 15.0))

